### ISSUE TITLE
CNKI知网无法自动获取文献信息

### ISSUE THREAD

**Issue by ouening** [Zotero-CN/translators_CN#1]
使用最新的CNKI.js之后还是无法通过zotero connector插件获取文献信息，浏览器和zotero都重启过了还是不行，点击插件之后过一会就自动消失，估计是CNKI接口变动太大了，还望作者及时修复，感谢！并对作者的无私奉献精神表示致敬！

**Comment by derek5290** [comment]
同样问题，求解决方案

**Comment by l0o0** [comment]
@derek5290 @ouening 两位朋友是在搜索结果的网页不能有结果，还是单个文献的页面不能收集引文信息。我最近发现知网的接口好像又变了，今天上午刚更新了下，可以试试下效果

**Comment by ouening** [comment]
两种情况下都有点问题：
1. 在搜索结果下点击保存文献可以识别文献信息，但不会自动下载pdf；
2. 在单个文献情况下，有的可以正常获取文献信息并且下载pdf（关闭了代理，有时是重复几次才正常），但有些文献又无法正常获取（重复几次、重启浏览器都没用），只得到了一个标题，后面加上了中国知网字样，如下图所示：
![image](https://user-images.githubusercontent.com/15122811/69608139-bbfccb00-1061-11ea-86c9-f142df50a6d0.png)

**Comment by l0o0** [comment]
@ouening  
1. 搜索结果那里，我暂时没有办法找到PDF之类的下载链接，所以目前没有办法  
2. 从你的截图上个，单页文献的结果是一个网页快照，好像没有识别成功。正确情况下，你可以从网页上下载PDF么？

**Comment by ouening** [comment]
正常是可以下载pdf的，我另外用火狐浏览器试了可以下载，但在火狐下有些文献不行，通过对比后发现还是用谷歌稳定一点，两者互补一下，有些就实在不行了。不知道是不是cnki的接口不断变动的原因，希望bug反馈对作者改进该插件有帮助！

**Comment by l0o0** [comment]
@ouening 确实可能存在不稳定的情况，而且下载时还有可能下载失败

**Comment by jbz79** [comment]
> 使用最新的CNKI.js之后还是无法通过zotero connector插件获取文献信息，浏览器和zotero都重启过了还是不行，点击插件之后过一会就自动消失，估计是CNKI接口变动太大了，还望作者及时修复，感谢！并对作者的无私奉献精神表示致敬！

纯小白来问咋用这个插件啊...放到components\或者extensions\下边好像没啥变化，谢谢啦

**Comment by l0o0** [comment]
@jbz79 要放到zotero 目录下的translators文件夹下，重启后可以用了
